- name: app setup
  ansible.builtin.import_roles:
   name: common
   tasks_from: app-setup.yaml

- name: app setup
  ansible.builtin.import_roles:
   name: common
   tasks_from: nodejs.yaml

- name: system setup
  ansible.builtin.import_roles:
   name: common
   tasks_from: system-setup.yaml