- name : install maven
  ansible.builtin.dnf :
    name : "{{ item }}"
    state : present
  loop :
  - maven
  - mysql

- name : Install dependencies
  ansible.builtin.command : mvn clean package
  args:
    chdir: /app  


- name : move jar file
  ansible.builtin.command: mv target/{{ component }}-{{ Version }}.jar {{ component }}.jar
  args :
    chdir: /app 